### ISSUE TITLE
[Bug]: GUI does not start

### ISSUE THREAD

**Issue by TheButterbrotMan** [Griefed/ServerPackCreator#178] opened 2022-01-16 21:34 UTC
### What happened?

I open the .exe java background process get started, but GUI does not open.

### What did you expect to happen?

GUI should open

### Version

3.0.0-alpha.15 (Alpha)

### Relevant log output

```shell
2022-01-16T22:30:00,368 DEBUG [main] (JarUtilities.java:158) - jarPath: D:/Programme/ServerPackCreator/ServerPackCreator-3.0.0-alpha.15.exe
2022-01-16T22:30:00,498 DEBUG [main] (ApplicationProperties.java:216) - Fallbackmodslist set to: [AdvancementPlaques-, AmbientSounds_, backtools-, BetterAdvancements-, BetterAnimationsCollection-, BetterDarkMode-, betterf3-, BetterF3-, BetterFoliage-, BetterPingDisplay-, BetterPlacement-, Blur-, catalogue-, cherishedworlds-, classicbar-, clickadv-, ClientTweaks_, configured-, Controlling-, CraftPresence-, CTM-, customdiscordrpc-, CustomMainMenu-, defaultoptions-, DefaultOptions_, desiredservers-, Ding-, drippyloadingscreen-, drippyloadingscreen_, Durability101-, dynmus-, dynamic-music-, DynamicSurroundings-, DynamicSurroundingsHuds-, eiramoticons-, EiraMoticons_, EnchantmentDescriptions-, EquipmentCompare-, extremesoundmuffler-, extremeSoundMuffler-, Fallingleaves-, fallingleaves-, fancymenu_, findme-, flickerfix-, FpsReducer-, FullscreenWindowed-, WindowedFullscreen-, InventoryEssentials_, InventorySpam-, invtweaks-, InventoryTweaks-, ItemBorders-, itemzoom, itlt-, jeed-, jeiintegration_, JustEnoughProfessions-, JEITweaker-, justenoughbeacons-, JustEnoughCalculation-, jehc-, just-enough-harvestcraft-, JustEnoughProfessions-, JustEnoughResources-, keywizard-, konkrete_, lazydfu-, LegendaryTooltips-, LightOverlay-, light-overlay-, LLOverlayReloaded-, loadmyresources_, lootbeams-, mcbindtype-, modnametooltip_, modnametooltip-, moreoverlays-, MouseTweaks-, multihotbar-, MyServerIsCompatible-, Neat, NotifMod-, OldJavaWarning-, ornaments-, overloadedarmorbar-, PackMenu-, PickUpNotifier-, Ping-, preciseblockplacing-, presencefootsteps-, PresenceFootsteps-, ReAuth-, ResourceLoader-, shutupexperimentalsettings-, SimpleDiscordRichPresence-, smoothboot-, sounddeviceoptions-, SpawnerFix-, spoticraft-, tconplanner-, timestamps-, Tips-, TipTheScales-, Toast Control-, Toast-Control-, torohealth-, toughnessbar-, TravelersTitles-, WorldNameRandomizer-]
2022-01-16T22:30:00,498 DEBUG [main] (ApplicationProperties.java:233) - Directories to exclude set to: [overrides, packmenu, resourcepacks, server_pack, fancymenu]
2022-01-16T22:30:00,499 DEBUG [main] (ApplicationProperties.java:250) - Directories which must always be included set to: [mods, config, defaultconfigs, scripts, saves, seeds, libraries]
2022-01-16T22:30:00,517 DEBUG [main] (LocalizationManager.java:227) - Using language-definitions from file on filesystem.
2022-01-16T22:30:00,518 DEBUG [main] (Main.java:126) - Gathering system information to include in log to make debugging easier.
2022-01-16T22:30:00,518 DEBUG [main] (Main.java:130) - Warning user about possible data loss.
2022-01-16T22:30:00,518  WARN [main] (Main.java:131) - ################################################################
2022-01-16T22:30:00,518  WARN [main] (Main.java:132) - #                      WORK IN PROGRESS!                       #
2022-01-16T22:30:00,519  WARN [main] (Main.java:133) - #  USE AT YOUR OWN RISK! BE AWARE THAT DATA LOSS IS POSSIBLE!  #
2022-01-16T22:30:00,519  WARN [main] (Main.java:134) - #        I WILL NOT BE HELD RESPONSIBLE FOR DATA LOSS!         #
2022-01-16T22:30:00,519  WARN [main] (Main.java:135) - #                    YOU HAVE BEEN WARNED!                     #
2022-01-16T22:30:00,519  WARN [main] (Main.java:136) - ################################################################
2022-01-16T22:30:00,520  INFO [main] (Main.java:139) - SYSTEM INFORMATION:
2022-01-16T22:30:00,520  INFO [main] (Main.java:140) - ServerPackCreator version: 3.0.0-alpha.15

2022-01-16T22:30:00,520  INFO [main] (Main.java:141) - JAR Path: D:/Programme/ServerPackCreator/ServerPackCreator-3.0.0-alpha.15.exe
2022-01-16T22:30:00,520  INFO [main] (Main.java:142) - JAR Name: ServerPackCreator-3.0.0-alpha.15.exe
2022-01-16T22:30:00,521  INFO [main] (Main.java:143) - Java version: 17.0.1
2022-01-16T22:30:00,521  INFO [main] (Main.java:144) - OS architecture: amd64
2022-01-16T22:30:00,521  INFO [main] (Main.java:145) - OS name: Windows 10
2022-01-16T22:30:00,521  INFO [main] (Main.java:146) - OS version: 10.0
2022-01-16T22:30:00,522  INFO [main] (Main.java:147) - Include this information when reporting an issue on GitHub.
2022-01-16T22:30:00,522 DEBUG [main] (LocalizationManager.java:302) - Language key "updates.log.info.none" not found for locale "en_us". Using JAR-resources fallback from "en_US".
```

### Anything else you would like to add?

Now i need to .zip my modpack manually.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment] 2022-01-17 07:31
Heya,

thank you very much for opening this as an issue on here on GitHub. As I mentioned in our Discord conversation, I will take a look at this once I'm back home from work.

Cheers,
Griefed

**Comment by Griefed** [comment] 2022-01-17 07:37
This is interesting. Running the `.jar` yielded the following result:
```
2022-01-17T08:36:00,922  INFO [main] (Main.java:141) - JAR Path: F:/temp/Neuer Ordner/ServerPackCreator-3.0.0-alpha.15.jar
2022-01-17T08:36:00,922  INFO [main] (Main.java:142) - JAR Name: ServerPackCreator-3.0.0-alpha.15.jar
2022-01-17T08:36:00,922  INFO [main] (Main.java:143) - Java version: 1.8.0_311
2022-01-17T08:36:00,923  INFO [main] (Main.java:144) - OS architecture: amd64
2022-01-17T08:36:00,923  INFO [main] (Main.java:145) - OS name: Windows 10
2022-01-17T08:36:00,923  INFO [main] (Main.java:146) - OS version: 10.0
2022-01-17T08:36:00,923  INFO [main] (Main.java:147) - Include this information when reporting an issue on GitHub.
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.NumberFormatException: For input string: "15
"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at de.griefed.serverpackcreator.utilities.versionchecker.VersionChecker.isNewAlphaAvailable(VersionChecker.java:159)
        at de.griefed.serverpackcreator.utilities.versionchecker.VersionChecker.isUpdateAvailable(VersionChecker.java:77)
        at de.griefed.serverpackcreator.utilities.versionchecker.VersionChecker.checkForUpdate(VersionChecker.java:54)
        at de.griefed.serverpackcreator.Main.main(Main.java:152)
        ... 8 more
```

Not only is the stacktrace not printed to the logs, but there's also a problem with my versionchecker.

**Comment by Griefed** [comment] 2022-01-17 12:11
I believe I found the cause for the problem (yay lunch break). The build process prints the new version into a VERSION.txt file which ServerPackCreator then reads and uses for various things. The problem? It adds a linebreak at the end. Said linebreak causes the `Integer.parseInt(...)` method to fail.

**Comment by Griefed** [comment] 2022-01-18 17:20
Please try [alpha.17](https://github.com/Griefed/ServerPackCreator/releases/tag/3.0.0-alpha.17) and see whether the issue is fixed for you.

**Comment by Griefed** [comment] 2022-01-19 17:20
People other than me using alpha.17 leads me to believe this issue is resolved.
I'm closing this ticket.
If you encounter anything else, please open a new issue.

Cheers,
Griefed

**Closed by Griefed** 2022-01-19 17:20 UTC
Labels: bug
