### ISSUE TITLE
[Feature request]: Detect Loader version from Pack

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#362] opened 2022-06-28 00:18 UTC
### Whats the feature you would like to be added?

![image](https://user-images.githubusercontent.com/3880072/176060640-4d3009b0-20fc-4414-9fdd-2302c07a2b8b.png)

Have that be able to detect the loader and version from the pack it's building from.

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment] 2022-06-28 04:40
Duplicate of #331. Furthermore, covered by https://git.griefed.de/Griefed/ServerPackCreator/-/issues/162.

**Closed** 2022-06-28 04:40 UTC
Labels: enhancement
