### ISSUE TITLE
[Bug]: Server Mods not getting copied

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Griefed/ServerPackCreator#453] opened 2023-03-17 02:03 UTC
### What happened?

In the last few builds when I do my first test run, often server mods are missing. The server does not start due to missing dependencies

### What did you expect to happen?

All mods except for those in the Clientside mod list are to be copied to the server mods folder

### Version

4.0.1

### Relevant log output
[modloader_installer.log](https://github.com/Griefed/ServerPackCreator/files/10997168/modloader_installer.log)
[serverpackcreator.log](https://github.com/Griefed/ServerPackCreator/files/10997169/serverpackcreator.log)

### Anything else you would like to add?

In this last case, it was the mods, Patchouli-1.18.2-71.1.jar and Incorporeal-3-forge-1.18.2-5.jar

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment] 2023-03-17 07:25
Heya ClaudiusMinimus,

thanks for opening this issue and for including the serverpackcreator.log!

I can confirm that both, Incorporeal-3-forge-1.18.2-5.jar and Patchouli-1.18.2-71.1.jar, should be included, as per their mods.toml definitions.

```toml
modLoader = "javafml"
loaderVersion = "[39,)"
license = "LGPL-3.0-or-later"
issueTrackerURL = "https://github.com/quat1024/incorporeal-3/issues"
logoFile = "wide_lores_banner.png"

[[mods]]
modId = "incorporeal"
version = "1.18.2-5"
displayName = "Incorporeal 3"
description = "Addon to a magic mod. More toys for Botania corporea dorks."
authors = "quaternary"
credits = "artemisSystem, Dudblockman, SnazzGass, jaredlll08, Darkhax, all the Botania nerds, and everyone who puts up with me"

[[dependencies.incorporeal]]
modId="forge"
mandatory=true
versionRange="[40.0.35,)"

[[dependencies.incorporeal]]
modId="botania"
mandatory=true
ordering="AFTER"
versionRange="*"
```

```toml
modLoader="javafml"
license="CC BY-NC-SA 3.0"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Vazkii/Patchouli"
logoFile="logo.png"

[[mods]]
modId="patchouli"
displayName="Patchouli"
version="${file.jarVersion}"
authors="Vazkii"
description='''
Accessible, Data-Driven, Dependency-Free Documentation for Minecraft Modders and Pack Makers
'''

[[dependencies.patchouli]]
modId="forge"
mandatory=true
versionRange="[40.1.51,)"
```

So this is definitely a bug in the autodetection-system. I'll fix it in the coming days.
In the meantime, you may include them in your server pack by either

1. [Deactivating the autodetection-system](https://wiki.griefed.de/en/Documentation/ServerPackCreator/ServerPackCreator-Help#automatic-detection-of-clientside-only-mods), or
2. Specifying them as files to be included, which will override the auto-exclusion, using `mods/Patchouli-1.18.2-71.1.jar;mods/Patchouli-1.18.2-71.1.jar` and `mods/Incorporeal-3-forge-1.18.2-5.jar;mods/Incorporeal-3-forge-1.18.2-5.jar`

Cheers,
Griefed

**Comment by ClaudiusMinimus** [comment] 2023-03-17 14:32
Hey Griefed,

Glad the logs help. I know I appreciate it when players provide me with as much info as possible, so I like to do the same for others.

Thanks! This worked perfectly!
`mods/Patchouli-1.18.2-71.1.jar;mods/Patchouli-1.18.2-71.1.jar` and `mods/Incorporeal-3-forge-1.18.2-5.jar;mods/Incorporeal-3-forge-1.18.2-5.jar`

I realized this may also solve another issue I have had. In the past, I have to go in and manually delete the config files/folders I want to be excluded. However, I could just include the files/folders as I did above.

Thanks again!
CM

**Comment by ClaudiusMinimus** [comment] 2023-03-17 15:14
I just tried to apply the same to my configs using this
```
config/ftbquests;config/ftbquests, config/bcc-common.toml;config/bcc-common.toml, config/spawnermod.json;config/spawnermod.json, defaultconfigs, kubejs, mods, patchouli_books, mods/Patchouli-1.18.2-71.1.jar;mods/Patchouli-1.18.2-71.1.jar, mods/Incorporeal-3-forge-1.18.2-5.jar;mods/Incorporeal-3-forge-1.18.2-5.jar
```
Also tried:
config/ftbquests, config/bcc-common.toml;config/bcc-common.toml, config/spawnermod.json;config/spawnermod.json, defaultconfigs, kubejs, mods, patchouli_books, mods/Patchouli-1.18.2-71.1.jar;mods/Patchouli-1.18.2-71.1.jar, mods/Incorporeal-3-forge-1.18.2-5.jar;mods/Incorporeal-3-forge-1.18.2-5.jar
```
However, `config/ftbquests` was copied to `/ftbquests`
![image](https://user-images.githubusercontent.com/17887664/225945358-6b71d9a4-fca3-4709-a3fd-bc7a3a0f8e68.png)

**Comment by Griefed** [comment] 2023-03-17 17:46
Thank you very much for the detailed information regarding your issue(s) with ServerPackCreator!

You have no idea how much this helps with debugging, finding the issue and fixing it. 😁

**Comment by Griefed** [comment] 2023-03-17 23:00
Both issues have been fixed in [4.0.3](https://github.com/Griefed/ServerPackCreator/releases/tag/4.0.3). Please give it a go. :)

Cheers,
Griefed

**Comment by ClaudiusMinimus** [comment] 2023-03-18 03:28
Will do, I'm doing a build tomorrw.

**Comment by alterNERDtive** [comment] 2023-03-22 18:04
Hello!

I seem to be having a similar issue. `appleskin`, `ArchitectsPalette` and `Patchouli` wouldn’t be copied. After upgrading from 4.0.0 to 4.0.4, it’s fixed for the latter two; `appleskin` still will not be copied.

I am assuming that is because [it _incorrectly_ states being client only](https://www.curseforge.com/minecraft/mc-mods/appleskin) in its `mods.toml` (removing the line in there fixes it). I would, however, expect it to be included nonetheless if I add it to the inclusion list. Which it, sadly, is not.

Also your wiki seems to be experiencing issues so I cannot try the “disable auto detection” fix :)

**Comment by Griefed** [comment] 2023-03-22 18:34
Heya alterNERDtive,

how did you try to include appleskin in your server pack? 

Thanks for the info about the wiki. :D I'll take a look.

**Comment by alterNERDtive** [comment] 2023-03-22 18:35
I added `mods\appleskin-forge-mc1.18.2-2.4.1.jar` to the “Directories and files to add:” list.

**Comment by Griefed** [comment] 2023-03-22 18:43
Ahh okay I see! That probably resulted in the file being copied to the base directory of the server pack, correct? 

In order to include that file in the mods-dir in the server pack, you need to specify the inclusion like so:

`mods\appleskin-forge-mc1.18.2-2.4.1.jar;mods\appleskin-forge-mc1.18.2-2.4.1.jar`

That should do the trick! :) I'd point to the wiki, but it's down, as you've already pointed out. 😅

**Comment by alterNERDtive** [comment] 2023-03-22 18:46
> That probably resulted in the file being copied to the base directory of the server pack, correct?

Nope.

![image](https://user-images.githubusercontent.com/53827887/227006253-b32bdde3-f8ea-444b-9672-2e1907f4b0a4.png)
![image](https://user-images.githubusercontent.com/53827887/227006300-99fcda97-edcd-48f8-9bf4-db34544efe5b.png)

**Comment by Griefed** [comment] 2023-03-22 19:04
Yeah I see the issue, and can confirm from my end that `mods\appleskin-forge-mc1.18.2-2.4.1.jar;mods\appleskin-forge-mc1.18.2-2.4.1.jar` does indeed not work, and I know exactly why.

I blame being tired, but really I just didn't notice this little bugger: `\`

For explicit file inclusion you need to use `/`, for example: `mods/appleskin-forge-mc1.19-2.4.2.jar;mods/appleskin-forge-mc1.19-2.4.2.jar`, which would result in your desired outcome. 😊

**Comment by Griefed** [comment] 2023-03-22 19:05
Out of curiosity: Which modpack did you run SPC with? I'd like to run a couple of tests regarding the automatic exclusion and appleskin being excluded (which it should, it is a clientside mod, after all. I f another mod specifies it as a dependency, and that mod is NOT a clientside mod, appleskin should still be included)

**Comment by Griefed** [comment] 2023-03-22 19:06
Aaaaand another note: Thanks for notifying me about the wiki. All working now. 😀

**Comment by alterNERDtive** [comment] 2023-03-22 19:25
> For explicit file inclusion you need to use `/`, for example: `mods/appleskin-forge-mc1.19-2.4.2.jar;mods/appleskin-forge-mc1.19-2.4.2.jar`, which would result in your desired outcome. 😊

Hmm, that does not work for me. It neither ends up in `mods` nor in the root folder. Running on Windows if that is relevant.

**Comment by Griefed** [comment] 2023-03-22 19:33
Aye, a target is required for file inclusions. At least on my end, running 4.0.4, an explicit inclusion didn't work with `\`, but it did with `/`. Eh, as long as it works now. :)

**Comment by Griefed** [comment] 2023-03-28 06:36
I assume this is now fixed, as alterNERDtive's usage and mine, too, resulted in the expected files being copied to the expected destinations. I'll go ahead and close this issue. Feel free to reopen it, should it indeed not be fixed.

Cheers,
Griefed

**Closed by Griefed** 2023-03-28 06:36 UTC
Labels: bug
