### ISSUE TITLE
[Bug]: doesn't filter out mods i said were client side

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#255] opened 2022-02-23 23:31 UTC
### What happened?

doesn't filter out mods i said were client side

using beta.4

i can tell because I can see them in the server pack

### What did you expect to happen?

not have my client sided mods in the server pack

### Version

3.0.0 beta.4

### Relevant log output

```shell
https://gist.github.com/a7cfd70f6529830f5969052193b15a9b
```

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment] 2022-02-24 08:53
Heya Kreezxil,

thanks for reporting this issue.
Unfortunately, I can not reproduce this behaviour on my part.
I've downloaded and installed World Of Dragons II, installed DefaultOptions & Neat & some other missing mods which were mentioned in your configuration, and ran with the same configuration as you did. The mentioned mods are not in the server pack generated by beta.4.

Can you check whether your `serverpackcreator.properties` has the following entry set to true?
`de.griefed.serverpackcreator.serverpack.cleanup.enabled`

If said property is set to `true`, set it to `false` and try again, please.

Cheers,
Griefed

**Comment by kreezxil** [comment] 2022-02-24 12:22
fancy menu showed up in it.

**Comment by Griefed** [comment] 2022-02-24 12:37
World Of Dragons II comes with `fancymenu_forge_2.6.3_MC_1.16.2-1.16.5.jar`, not `fancymenu_2.2.2-2_MC_1.16.2-1.16.5.jar`.

You may have an outdated configuration for your server pack. As in, you updated Fancy Menu, but did not update your ServerPackCreator configuration to reflect this update.

Going forward, I suggest you use the format of the fallback modslist, which specifies clientside-only mods like this:
- `torchoptimizer-`
- `DefaultOptions_`
- `defaultoptions-`
- `fancymenu_`

That way, it doesn't matter if a mod gets updated. As long as the mod-author doesn't change the formatting of their JARs name, it will get caught by ServerPackCreator.

**Comment by Griefed** [comment] 2022-02-24 13:10
I checked your logs again and found a debug entry:

> 2022-02-23T14:02:51,740 DEBUG [pool-2-thread-1] (ServerPackHandler.java:1255) - Copying: /home/kreezxil/.config/gdlauncher_next/instances/World of Dragons II/mods/fancymenu_forge_2.6.3_MC_1.16.2-1.16.5.jar

It was indeed an outdated ServerPackCreator configuration. 

I'm closing this issue. Should you encounter anything else, please feel free to open a new issue. 

Until then. Take care and stay safe.

Cheers,
Griefed

**Closed by Griefed** 2022-02-24 13:10 UTC
Labels: bug

**Comment by kreezxil** [comment] 2022-02-25 01:08
i was under the impression it can fitler out the client sided mods, also if
i tell it some mods to exclude, can't it figure out anything about the mods
so that if they update, it can say "oh look the first 10 characters match
up to version part" and just update itself.

**Comment by Griefed** [comment] 2022-02-25 08:48
> i was under the impression it can fitler out the client sided mods,

ServerPackCreator has a autodetection system. However, due to the chaotic nature of Forge modding, not every clientside-only mod can be caught. That is due to be dependency declarations in the mods.toml-files of the mods. Nothing I can do about that but work with what they give me.

> also if i tell it some mods to exclude, can't it figure out anything about the mods so that if they update, it can say "oh look the first 10 characters match up to version part" and just update itself.

Yeah, I've thought about this many times. That is why one can specify `fancymenu_`, `torchoptimizer-` etc., so new version can be caught.

I have no way of knowing when the name of the mod ends and the versioning begins. If there were a simple way to implement this, and most importantly a reliable way, it would have already been implemented a long time ago. ;-)

**Comment by kreezxil** [comment] 2022-02-25 11:21
holy crap, you just thought of it and you didn't realize it. put a "!"
button on the field to explain it. As it's a warning.

Have it say this.

"Use the browser to quickly load your client side mods into this field. If
you do not change the file names they will be treated as constants. It is
recommend you edit the fields to use asterisks in place of the file name
parts that will change between updates. For example fancymenu*, would
exclude all fancymenu each time and not just a specific version. The
asterisk wildcard can go anywhere and as much as want, but you only need
the one. Cheers to Kreezxil for this one!"

**Comment by Griefed** [comment] 2022-02-25 16:16
Already mentioned in the README **https://github.com/Griefed/ServerPackCreator#5-configuration**:

<html>
<body>


clientMods | List of client-side only mods which are to be deleted from the serverpack. You only need to specify the beginning of the filename up, but excluding, the version number. ServerPackCreator checks whether any of the mods which are copied from the modpack to the serverpack start with any strings in this list and, if there's a match, deletes that file from the serverpack. Check out the example for an idea of how it's supposed to look.
-- | --

</body>
</html>

Though I do agree that this should be added to the help text in the GUI.

**Comment by Griefed** [comment] 2022-02-25 16:26
Adding said text, or parts of it, to a tooltip would be overkill and a tooltip/help button would be too much as well, as there is already the help section and well, the README :D
